config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  resources :categories do
    resources :posts do
      resources :comments
      match 'photos/:id', to: 'posts#delete_photo', via: :delete,
                          as: 'delete_photo'
    end
    get 'posts/:id/deactivate', to: 'posts#deactivate',
                                as: 'post_deactivate'
  end
  get 'my_posts', to: 'posts#my_posts'
  post 'search', to: 'posts#search'
  get 'auth/:provider/callback', to: 'sessions#create'
  get 'auth/failure', to: redirect('/')
  get 'signout', to: 'sessions#destroy', as: 'signout'
  resources :sessions, only: %i[create destroy]
  resource :home, only: [:show]
  root to: 'categories#index'
end

app/models/comment.rb
# frozen_string_literal: true

# Add database interactions for comments here
class Comment < ApplicationRecord
  has_ancestry
  belongs_to :commentable, polymorphic: true
  validates :content, presence: true
  belongs_to :user

  PER_PAGE = 30
end

app/controllers/comments_controller.rb
# frozen_string_literal: true

# This controller provides comments functionality
class CommentsController < ApplicationController
  before_action :load_commentable, :set_category

  def index
    @comments = @commentable.comments.order('created_at desc')
                            .page(params[:page]).per(Comment::PER_PAGE)
  end

  def new
    @comment = @commentable.comments.order('created_at desc')
                           .new(parent_id: params[:parent_id])
    respond_to do |format|
      format.html { render partial: 'form' }
      format.js
    end
  end

  def create
    @comment = @commentable.comments.new(comment_params)
    @comment.user_id = current_user.id
    @comment.save
    redirect_to [@category, @commentable]
  end

  def destroy
    @comment = Comment.find(params[:id])
    authorize @comment, :destroy?
    @comment.destroy
    respond_to do |format|
      format.html do
        redirect_to category_post_path(@category, @commentable),
                    notice: 'Comment deleted successfully'
      end
      format.json { head :no_content }
    end
  end

  private

  def comment_params
    params.require(:comment).permit(:content, :commentable_id,
                                    :commentable_type, :parent_id)
  end

  def set_category
    @category = Category.find params[:category_id]
  end

  def load_commentable
    resource, id = request.path.split('/')[3..4]
    @commentable = resource.singularize.classify.constantize.find(id)
  end
end

app/helpers/comments_helper.rb
# frozen_string_literal: true

# These methods will be used in comment views
module CommentsHelper
  def nested_messages(messages)
    return if messages.blank?
    messages.map do |message, sub_messages|
      render(partial: 'comments/comment', locals: { message: message }) +
        content_tag(:div, nested_messages(sub_messages),
                    class: 'nested_messages')
    end.join.html_safe
  end

  def submit_text
    @comment.parent.present? ? 'Reply' : 'Add Comment'
  end

  def content_field(f)
    if @comment.parent.present?
      f.text_field :content, class: 'form-control'
    else
      f.text_area :content, rows: 8, class: 'form-control'
    end
  end
end

app/views/comments/_comment.html.erb
<div class='comment'>
  <strong><%= message.user.name %></strong> | 
  <%= message.created_at.strftime("%d %b %Y %H:%M:%S ") %>
  <% if policy(message).destroy? %>
    | <%= link_to 'Destroy', category_post_comment_path(@category, @post, message), 
        method: :delete, remote: true, data: { confirm: "Are you sure?"} %>
	<% end %><br/><br/>
  <%= message.content %><br/><br/>
  <%= link_to 'Reply', new_category_post_comment_path(@category, @commentable,
    parent_id: message), id: "reply_link_#{message.id}", remote: true %>
  <div id="reply_text_box_#{message.id}"></div>
  <hr/>
</div>

app/views/comments/_comments.html.erb
<h3>Comments</h3><hr/>
<%= nested_messages @comments.arrange(order: "created_at DESC")  %>

app/views/comments/_form.html.erb
<%= form_for [@category, @commentable, @comment], remote: true do |f| %>
	<% if @comment.errors.any? %>
		<div class='error_messages'>
			<h2>Please correct the following errors.</h2>
			<ul>
				<% @comment.errors.full_messages.each do |message| %>
					<li><%= message %></li>
				<% end %>
			</ul>
		</div>
	<% end %>
	<%= f.hidden_field :parent_id %>
	<div class='field'>
		<%= content_field(f) %>
	</div>
	<div class='actions'>
		<%= f.submit submit_text, class: "btn btn-default navbar-btn" %>
	</div>
<% end %>

app/views/comments/new.js.erb
var reply_id = '#reply_link_' + <%= @comment.parent_id.to_s %>;
$(reply_id).hide().after('<%= j render("form") %>')