config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  resources :categories do
    resources :posts do
      resources :comments
      match 'photos/:id', to: 'posts#delete_photo', via: :delete,
                          as: 'delete_photo'
    end
    get 'posts/:id/deactivate', to: 'posts#deactivate',
                                as: 'post_deactivate'
  end
  get 'my_posts', to: 'posts#my_posts'
  post 'search', to: 'posts#search'
  get 'auth/:provider/callback', to: 'sessions#create'
  get 'auth/failure', to: redirect('/')
  get 'signout', to: 'sessions#destroy', as: 'signout'
  resources :sessions, only: %i[create destroy]
  resource :home, only: [:show]
  root to: 'categories#index'
end

app/models/post.rb
# frozen_string_literal: true

# This is a model for posts
class Post < ApplicationRecord
  validates :title, presence: true, length: { maximum: 250 }
  validates :description, presence: true, length: { maximum: 65_530 }
  validates :address, presence: true, length: { maximum: 65_530 }
  validates :contact_number, length: { minimum: 10, maximum: 15 }
  validates_format_of :contact_number,
                      with: /\d[0-9]\)*\z/,
                      message: ': only positive number without
                       spaces are allowed'
  validates :price, numericality: { greater_than: 0, less_than: 10_000_000_000 }
  belongs_to :category
  belongs_to :user
  has_many :comments, as: :commentable
  has_many :pictures, dependent: :destroy

  PER_PAGE = 30
  scope :active, -> { where('deactivated = ? or deactivated = ?', false, nil) }
end

app/controllers/posts_controller.rb
# frozen_string_literal: true

# This class provides the CRUD for posts
# rubocop:disable ClassLength
class PostsController < ApplicationController
  before_action :require_authentication, except: %i[index show search]
  before_action :set_category, except: %i[my_posts search]
  before_action :set_post, only: %i[show edit update destroy deactivate]

  # GET /posts
  # GET /posts.json
  def index
    @posts = @category.posts.active.order(created_at: :desc)
                      .page(params[:page]).per(Post::PER_PAGE)
  end

  # GET /posts/1
  # GET /posts/1.json
  def show
    @commentable = @post
    @comments = @commentable.comments.order(created_at: :desc)
    @comment = Comment.new
    @pictures = @post.pictures
  end

  # GET /posts/new
  def new
    @post = Post.new
    authorize Post, :new?
  end

  # GET /posts/1/edit
  def edit
    authorize @post, :edit?
    @pictures = @post.pictures
  end

  # POST /posts
  # POST /posts.json
  # rubocop:disable MethodLength
  def create
    @post = build_post
    respond_to do |format|
      if @post.save
        add_images
        format.html do
          redirect_to category_post_path(@category, @post),
                      notice: 'Post was successfully created.'
        end
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1
  # PATCH/PUT /posts/1.json
  # rubocop:disable Metrics/AbcSize
  def update
    authorize @post, :update?
    respond_to do |format|
      if @post.update(post_params)
        add_images
        format.html do
          redirect_to category_post_path(@category, @post),
                      notice: 'Post was successfully updated.'
        end
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    authorize @post, :destroy?
    @post.destroy
    respond_to do |format|
      format.html do
        redirect_to category_posts_path(@category),
                    notice: 'Post was successfully destroyed.'
      end
      format.json { head :no_content }
    end
  end

  def my_posts
    @posts = current_user.posts.order(created_at: :desc)
                         .page(params[:page]).per(Post::PER_PAGE)
    render :index
  end

  def delete_photo
    photo = Picture.find(params['id'])
    post = photo.post
    photo.destroy
    redirect_to edit_category_post_path(@category, post)
  end

  def search
    search_keyword = params[:search_keyword]
    @posts = Post.where('title like :q or description like :q',
                        q: "%#{search_keyword}%")
    @posts = @posts.order(created_at: :desc).page(params[:page])
                   .per(Post::PER_PAGE)
    render :index
  end

  def deactivate
    authorize @post, :destroy?
    @post.deactivated = true
    @post.deactivation_date = Time.now
    if @post.save
      respond_to do |format|
        format.html do
          redirect_to category_posts_path(@category),
                      notice: 'Post was successfully deactivated!!'
        end
        format.json { head :no_content }
      end
    else
      format.html do
        redirect_to category_posts_path(@category),
                    notice: 'Unable to deactivate this post'
      end
      format.json { render json: @post.errors, status: :unprocessable_entity }
    end
  end

  private

  def add_images
    params[:images]&.each { |image| @post.pictures.create(image: image) }
  end

  def build_post
    post = Post.new(post_params)
    post.user = current_user
    post.category = @category
    post
  end

  # Use callbacks to share common setup or constraints between actions.
  def set_post
    @post = Post.active.find(params[:id])
    authorize @post
  end

  def set_category
    @category = Category.find params[:category_id]
  end

  # Never trust parameters from the scary internet,
  # only allow the white list through.
  def post_params
    params.require(:post).permit(:title, :description, :address, :price,
                                 :price, :contact_number, :deactivated,
                                 :deactivation_date)
  end
end

app/helpers/posts_helper.rb
# frozen_string_literal: true

# These methods will be used in post views
module PostsHelper
  def price_text(category)
    case category.name
    when 'Flats for rent', 'Vacancy for room mate'
      return 'Monthly Rent (Rs)'
    when 'Sell a car', 'Sell a bike'
      return 'Total Price (Rs)'
    else
      'Price (Rs)'
    end
  end
end

app/views/posts/_form.html.erb
<%= form_with(model: [@category, @post], local: true, :html => {  
  multipart: true }) do |form| %>
  <% if post.errors.any? %>
    <div id="error_explanation" class='form-group col-md-8'>
      <h3><%= pluralize(post.errors.count, "error") %> prohibited this post from being saved:</h3>
      <ul>
      <% post.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group col-md-8">
    <%= form.label :title %>
    <%= form.text_field :title, id: :post_title, class: 'form-control' %>
  </div>

  <div class="form-group col-md-8">
    <%= form.label :description %>
    <%= form.text_area :description, id: :post_description, class: 'tinymce' %>
  </div>

  <div class="form-group col-md-8">
    <%= form.label :address %>
    <%= form.text_field :address, id: :post_address, class: 'form-control' %>
  </div>

  <div class="form-group col-md-8">
    <%= form.label "Price (Rs)" %>
    <%= form.text_field :price, id: :post_price, class: 'form-control' %>
  </div>

  <div class="form-group col-md-8">
    <%= form.label :contact_number %>
    <%= form.text_field :contact_number, id: :post_contact_number, class: 'form-control' %>
  </div>

  <div class="form-group col-md-8">
    <%= form.label :pictures %>
    <div>
      <%= file_field_tag "images[]", type: :file, multiple: true %>
    </div>
  </div>

  <div class="form-group col-md-8">
    <% @pictures&.each do |photo| %>
      <span class="wrapper">       
         <%= link_to category_post_delete_photo_path(post.category, post, photo), method: :delete, 
                  data: { confirm: 'Are you sure?' }, class: "img-link" do %>
          <i class='glyphicon glyphicon-remove'  data-toggle='tooltip' 
              data-placement='left' title='Delete'></i>
           <%= image_tag photo.image.url, size: '200x150' %>
          <% end %>
      </span>
    <% end %>
  </div>

  <div class="form-group col-md-8">
    <%= form.submit "Submit", class: "btn btn-default" %>
  </div>
<% end %>
<%= tinymce %>

app/views/posts/edit.html.erb
<h3>Editing Post: </h3>
<%= render 'form', post: @post %>
<div class="form-group col-md-8">
  <%= link_to 'Show', category_post_path(@category, @post) %> |
  <%= link_to 'Back', :back %>
</div>

app/views/posts/index.html.erb
<div class="container">
  <% if @category %>
    <%= link_to 'New Post', new_category_post_path(@category), 
    class: 'btn btn-default' if policy(Post).new? %>
  <% else %>
    <%= link_to 'Select Category', categories_path, class: 'btn btn-default' %>
  <% end %>

  <h2><%= @category.name if @category %></h2>
  <% @posts.each do |post| %>
    <div class="panel panel-success">
      <div class="panel-heading">
        <h3 class="panel-title">
          <%= link_to "#{post.title}", category_post_path(post.category, post) %>
          <% if policy(post).edit? %>
            <%= link_to edit_category_post_path(post.category, post) do %>
              <i class='glyphicon glyphicon-edit' data-toggle='tooltip' 
              data-placement='left' title="Edit"></i>
            <% end %>
            <%= link_to category_post_deactivate_path(post.category, post), 
                data: { confirm: 'Are you sure you want to deactivate this post?' } do %>
              <i class='glyphicon glyphicon-remove'  data-toggle='tooltip' 
              data-placement='left' title='Deactivate'></i>
            <% end %>
          <% end %>
        </h3>
      </div>
      <div class="panel-body">
        <p><%= post.address %></p>
        <p><%= price_text(post.category) %>: <%= post.price %></p>
      </div>
    </div>     
  <% end %>
  <%= paginate @posts %>
</div>

app/views/posts/new.html.erb
<h1>Form: <%= @category.name %></h1>
<%= render 'form', post: @post %>
<div class="form-group col-md-8">
  <%= link_to 'Back', :back %>
</div>

app/views/posts/show.html.erb
<div class="jumbotron">
	<p>
	  <strong><%= @post.title %></strong>
	</p>
	<p>
	  <i><%= @post.address %></i>
	</p>

	<p>
	  <strong>Description:</strong>
	</p>
	<p>
	  <%= sanitize @post.description %>
	</p>

	<p>
	  <strong><%= price_text(@category) %>:</strong>
	  <%= @post.price %>
	</p>

	<p>
	  <strong>Contact number:</strong>
	  <%= @post.contact_number %>
	</p>

  <p> 
	  <strong>Email:</strong>
	  <%= @post.user.email %>  	
  </p>
	<%= link_to 'Edit', edit_category_post_path(@category, @post) if policy(@post).edit? %> | 
	<%= link_to 'Back', category_post_path(@category) %>
</div>

<% unless @pictures.empty? %>
	<div id="myCarousel" class="carousel slide" data-ride="carousel">
	  <!-- Indicators -->
		<ol class="carousel-indicators">
		   <% @pictures.each_with_index do |photo, n| %>
		     <li data-target='#MyCarousel' data-slide-to="#{n}" class="#{'active' if n == 0}"></li>
		   <% end %>
		</ol>

		<div class="carousel-inner" role="listbox">
		  <div class="item active">
		    <%= image_tag @pictures.first.image.url %>
		  </div>
		  <% @pictures.drop(1).each do |photo| %>
		     <div class="item">
		       <%= image_tag photo.image.url %>
		     </div>
		  <% end %>
		</div>

	  <!-- Left and right controls -->
	  <a class="left carousel-control" href="#myCarousel" data-slide="prev">
	    <span class="glyphicon glyphicon-chevron-left"></span>
	    <span class="sr-only">Previous</span>
	  </a>
	  <a class="right carousel-control" href="#myCarousel" data-slide="next">
	    <span class="glyphicon glyphicon-chevron-right"></span>
	    <span class="sr-only">Next</span>
	  </a>
	</div>
<% end %>
<br/><br/>
<%= render 'comments/form' %>
<%= render 'comments/comments' %>