config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  resources :categories do
    resources :posts do
      resources :comments
      match 'photos/:id', to: 'posts#delete_photo', via: :delete,
                          as: 'delete_photo'
    end
    get 'posts/:id/deactivate', to: 'posts#deactivate',
                                as: 'post_deactivate'
  end
  get 'my_posts', to: 'posts#my_posts'
  post 'search', to: 'posts#search'
  get 'auth/:provider/callback', to: 'sessions#create'
  get 'auth/failure', to: redirect('/')
  get 'signout', to: 'sessions#destroy', as: 'signout'
  resources :sessions, only: %i[create destroy]
  resource :home, only: [:show]
  root to: 'categories#index'
end

app/models/category.rb
# frozen_string_literal: true

# This is a model for categories
class Category < ApplicationRecord
  validates :name, presence: true, uniqueness: true
  validates :description, presence: true
  has_many :posts, dependent: :destroy
end

app/controllers/categories_controller.rb
# frozen_string_literal: true

# This controller provides CRUD for category
class CategoriesController < ApplicationController
  before_action :require_authentication, except: %i[index show]
  before_action :set_category, only: %i[show edit update destroy]

  # GET /categories
  # GET /categories.json
  def index
    @categories = Category.all
  end

  # GET /categories/1
  # GET /categories/1.json
  def show; end

  # GET /categories/new
  def new
    @category = Category.new
  end

  # GET /categories/1/edit
  def edit; end

  # POST /categories
  # POST /categories.json
  # rubocop:disable MethodLength
  def create
    @category = Category.new(category_params)

    respond_to do |format|
      if @category.save
        format.html do
          redirect_to @category,
                      notice: 'Category was successfully created.'
        end
        format.json { render :show, status: :created, location: @category }
      else
        format.html { render :new }
        format.json do
          render json: @category.errors, status: :unprocessable_entity
        end
      end
    end
  end

  # PATCH/PUT /categories/1
  # PATCH/PUT /categories/1.json
  def update
    respond_to do |format|
      if @category.update(category_params)
        format.html do
          redirect_to @category, notice: 'Category was successfully updated.'
        end
        format.json { render :show, status: :ok, location: @category }
      else
        format.html { render :edit }
        format.json do
          render json: @category.errors, status: :unprocessable_entity
        end
      end
    end
  end

  # DELETE /categories/1
  # DELETE /categories/1.json
  def destroy
    @category.destroy
    respond_to do |format|
      format.html do
        redirect_to categories_url,
                    notice: 'Category was successfully destroyed.'
      end
      format.json { head :no_content }
    end
  end

  private

  def set_category
    @category = Category.find(params[:id])
    authorize @category
  end

  def category_params
    params.require(:category).permit(:name, :description)
  end
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/views/categories/_form.html.erb
<%= form_with(model: category, local: true) do |form| %>
  <% if category.errors.any? %>
    <div id="error_explanation" class='form-group col-md-8'>
      <h3><%= pluralize(category.errors.count, "error") %> prohibited this category from being saved:</h3>
      <ul>
      <% category.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class='form-group col-md-8'>
    <%= form.label :name %>
    <%= form.text_field :name, id: :category_name, class: 'form-control' %>
  </div>

  <div class='form-group col-md-8'>
    <%= form.label :description %>
    <%= form.text_area :description, id: :category_description, class: 'tinymce' %>
  </div>

  <div class='form-group col-md-8'>
    <%= form.submit "Submit", class: "btn btn-default" %>
  </div>
<% end %>
<%= tinymce %>

app/views/categories/edit.html.erb
<h1>Editing Category</h1>
<%= render 'form', category: @category %>
<div class="form-group col-md-8">
	<%= link_to 'Show', @category %> |
	<%= link_to 'Back', categories_path %>
</div>

app/views/categories/index.html.erb
<div class="container">
	<% if policy(Category).create? %>
	  <p class='bottom-margin'>
	    <%= link_to 'New Category', new_category_path,
		  class: "btn btn-default" %>
	  </p>
	<% end %>

	<% @categories.each do |category| %>
			<div class="panel panel-success">
			  <div class="panel-heading">
			    <h3 class="panel-title">
			      <%= link_to "#{category.name}", category_posts_path(category) %>
				    <% if policy(category).edit? %>	
					    <%= link_to edit_category_path(category) do %>
						    <i class='lyphicon glyphicon-edit' data-toggle='tooltip' 
						    data-placement='left' title="Edit"></i>
							<% end %>
					    <%= link_to category, method: :delete, data: { confirm: 'Are you sure?' } do %>
						    <i class='glyphicon glyphicon-remove'  data-toggle='tooltip' 
						    data-placement='left' title='Delete'></i>
							<% end %>
				    <% end %>
			    </h3>
			  </div>
			  <div class="panel-body">
			    <%= category.description.html_safe %>
			  </div>
			</div>
	<% end %>
</div>

app/views/categories/new.html.erb
<h1>New Category</h1>

<%= render 'form', category: @category %>
<div class="form-group col-md-8">
	<%= link_to 'Back', categories_path %>
</div>

app/views/categories/show.html.erb
<p>
  <strong>Name:</strong>
  <%= @category.name %>
</p>

<p>
  <strong>Description:</strong>
  <%= @category.description.html_safe %>
</p>

<%= link_to 'Edit', edit_category_path(@category) %> |
<%= link_to 'Back', categories_path %>