config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  resources :categories do
    resources :posts do
      resources :comments
      match 'photos/:id', to: 'posts#delete_photo', via: :delete,
                          as: 'delete_photo'
    end
    get 'posts/:id/deactivate', to: 'posts#deactivate',
                                as: 'post_deactivate'
  end
  get 'my_posts', to: 'posts#my_posts'
  post 'search', to: 'posts#search'
  get 'auth/:provider/callback', to: 'sessions#create'
  get 'auth/failure', to: redirect('/')
  get 'signout', to: 'sessions#destroy', as: 'signout'
  resources :sessions, only: %i[create destroy]
  resource :home, only: [:show]
  root to: 'categories#index'
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
  <title>Company Portal</title>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
  <%= csrf_meta_tags %>
  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
</head>
<body>
	<nav class="navbar navbar-inverse navbar-fixed-top">
	  <div class="container-fluid">
	    <div class="navbar-header">
	      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#myNavbar">
	        <span class="icon-bar"></span>
	        <span class="icon-bar"></span>
	        <span class="icon-bar"></span>                        
	      </button>
	      <a class="navbar-brand" href="/">Logo</a>
	    </div>

	    <div class="collapse navbar-collapse" id="myNavbar">
	      <ul class="nav navbar-nav">
	        <li><%= link_to "Home", categories_path %></li>
	      </ul>

	      <% if current_user %>
		      <ul class="nav navbar-nav">
		        <li><%= link_to "My Posts", my_posts_path %></li>
		      </ul>	
		      <ul class="nav navbar-nav navbar-right">
			      <li>
		          <%= link_to "Sign out", signout_path, id: "sign_out" %>
			      </li>
		      </ul>
		    <% else %>
		      <ul class="nav navbar-nav navbar-right">
			      <li>
		          <%= link_to "Sign in with Google", "/auth/google_oauth2", id: "sign_in" %>
			      </li>
		      </ul>
	      <% end %>

	      <ul class="nav navbar-nav navbar-right">
					<%= form_tag('/search', class: 'navbar-form navbar-right') do %>
						<div class="form-group input-group">
							<%= text_field_tag :search_keyword, nil, class: 'form-control',
							 placeholder: "Search.." %>
					   	<span class="input-group-btn">
		            <button class="btn btn-default" type="submit">
		              <span class="glyphicon glyphicon-search"></span>
		            </button>
		          </span>
  					</div>
					<% end %>
	      </ul>
	      

	      <ul class="nav navbar-nav navbar-right">
 					<% if current_user %>
		        <li>
			        <a href="#"><span class="glyphicon glyphicon-user"></span> 
									Welcome <strong><%= current_user.name %></strong>
			        </a>
		        </li>
					<% end %>
	      </ul>

	    </div>
	  </div>
	</nav>
	<div class="container main-container">
	  <div>
			<% if notice %> 
				<p class="alert alert-success">
					<%= notice %>
				</p>
			<% end %>
	  </div>
	  <div>
	    <%= yield %>
	  </div>
	</div>

	<footer class="container-fluid text-center">
    <div class="wpb_text_column wpb_content_element ">
      <div class="wpb_wrapper">
	      © 2017 Synerzip, Inc. All Rights Reserved | <a href="http://www.synerzip.com/privacy-policy/">Privacy Policy</a> | <a href="http://www.synerzip.com/disclaimer/">Disclaimer</a>
	    </div>
	  </div>
	</footer>

</body>
</html>